---
- name: CONFIGURE | Set health reporting telemetry setting
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "datareporting.healthreport.uploadEnabled"
    line: 'user_pref("datareporting.healthreport.uploadEnabled", {{ allow_health_reporting }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: CONFIGURE | Set study reporting telemetry setting
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "app.shield.outsidestudies.enabled"
    line: 'user_pref("app.shield.outsidestudies.enabled", {{ allow_study_reporting }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: CONFIGURE | Set whether to ask to save passwords
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "signon.rememberSignons"
    line: 'user_pref("signon.rememberSignons", {{ ask_save_passwords }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: CONFIGURE | Set whether to ask to use location
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "permissions.default.geo"
    line: 'user_pref("permissions.default.geo", {{ ask_use_location }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664
