---
- name: CONFIGURE | Load "{{ extension_id }}" status
  ansible.builtin.shell:
    cmd: "jq '(.addons[] | select(.id == \"{{ extension_id }}\").active)' {{firefox_config_folder_path }}/extensions.json"
  changed_when: False
  register: extension_active_status


- name: CONFIGURE | Set "{{ extension_id }}" status to enabled
  ansible.builtin.shell:
    cmd: "jq -c '(.addons[] | select(.id == \"{{ extension_id }}\").active) |= true' {{firefox_config_folder_path }}/extensions.json > /tmp/extensions.json && mv /tmp/extensions.json {{firefox_config_folder_path }}/extensions.json"
  when: extension_active_status.stdout == "false"

- name: CONFIGURE | Load "{{ extension_id }}" userDisabled status
  ansible.builtin.shell:
    cmd: "jq '(.addons[] | select(.id == \"{{ extension_id }}\").userDisabled)' {{firefox_config_folder_path }}/extensions.json"
  changed_when: False
  register: extension_userDisabled_status


- name: CONFIGURE | Set "{{ extension_id }}" userDisabled to false
  ansible.builtin.shell:
    cmd: "jq -c '(.addons[] | select(.id == \"{{ extension_id }}\").userDisabled) |= false' {{firefox_config_folder_path }}/extensions.json > /tmp/extensions.json && mv /tmp/extensions.json {{firefox_config_folder_path }}/extensions.json"
  when: extension_userDisabled_status.stdout == "true"
