---
# Also gets configured by General/Startup/Open previous windows and tabs
- name: CONFIGURE | Set startup page functionality
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "browser.startup.page"
    line: 'user_pref("browser.startup.page", {{ startup_page_option }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: CONFIGURE | Configure custom startup page
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "browser.startup.homepage"
    line: 'user_pref("browser.startup.homepage", "{{ startup_homepage }}");'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: CONFIGURE | Configure recommended stories
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: True
    regex: "browser.newtabpage.activity-stream.feeds.section.topstories"
    line: 'user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", {{ recommended_stories }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664
