---
- name: CONFIGURE | Determine whether about:config warning shows
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "browser.aboutConfig.showWarning"
    line: 'user_pref("browser.aboutConfig.showWarning", {{ browser_aboutconfig_showwarning }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Determine whether links open in a new tab
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "browser.tabs.loadInBackground"
    line: 'user_pref("browser.tabs.loadInBackground", {{ load_new_tab_in_background }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Configure find sound status
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "accessibility.typeaheadfind.enablesound"
    line: 'user_pref("accessibility.typeaheadfind.enablesound", {{ typeaheadfind_sound_enabled }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Configure vertical tab status
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: '"sidebar.verticalTabs"'
    line: 'user_pref("sidebar.verticalTabs", {{ vertical_tabs }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Configure vertical tab visibility
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "sidebar.visibility"
    line: 'user_pref("sidebar.visibility", "{{ sidebar_visibility }}");'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Dismiss vertical tab introduction
  when: vertical_tabs | bool
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "sidebar.verticalTabs.dragToPinPromo.dismissed"
    line: 'user_pref("sidebar.verticalTabs.dragToPinPromo.dismissed", true);'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Ensure sidebar is revamped
  when: vertical_tabs | bool
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "sidebar.revamp"
    line: 'user_pref("sidebar.revamp", {{ "true" if vertical_tabs else sidebar_revamp }});'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'

- name: CONFIGURE | Configure sidebar tools
  when: sidebar_tools is defined
  ansible.builtin.lineinfile:
    path: "{{ firefox_config_folder_path }}/user.js"
    create: true
    regex: "sidebar.main.tools"
    line: 'user_pref("sidebar.main.tools", "{{ sidebar_tools }}");'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0664'
