---
- name: INSTALL | Firefox
  tags:
  - install
  block:
    - name: INSTALL | Ensure firefox package is installed
      become: True
      ansible.builtin.package:
        name: firefox
        state: latest

    - name: INSTALL | Check firefox config folder exists
      ansible.builtin.find:
        path: "{{ ansible_user_dir }}/.mozilla/firefox"
        patterns: '^.*\.default-release'
        use_regex: True
        file_type: directory
      register: firefox_config_folder_search

    - name: INSTALL | Create firefox config folder
      block:
      - name: INSTALL | Start firefox if config folder does not exist
        ansible.builtin.shell:
          cmd: "firefox &"
        changed_when: False

      - name: INSTALL | Wait 10 seconds for firefox to start
        ansible.builtin.shell:
          cmd: "sleep 10"
        changed_when: False

      - name: INSTALL | Kill firefox process
        ansible.builtin.shell:
          cmd: "kill $(pidof firefox)"
        changed_when: False
      when: firefox_config_folder_search.matched == 0

- name: CONFIGURE | Firefox
  tags:
  - configure
  block:
    - name: CONFIGURE | Check firefox config folder exists
      ansible.builtin.find:
        path: "{{ ansible_user_dir }}/.mozilla/firefox"
        patterns: '^.*\.default-release'
        use_regex: True
        file_type: directory
      register: firefox_config_folder_search

    - name: CONFIGURE | Register firefox config folder as a fact
      ansible.builtin.set_fact:
        firefox_config_folder_path: "{{ firefox_config_folder_search.files[0].path }}"

    - name: CONFIGURE | Decide whether PDFs are downloaded when opened
      ansible.builtin.lineinfile:
        path: "{{ firefox_config_folder_path }}/user.js"
        create: True
        regex: "browser.download.open_pdf_attachments_inline"
        line: 'user_pref("browser.download.open_pdf_attachments_inline", {{ prevent_default_download_pdf }});'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0664

    - name: CONFIGURE | Remove tab close button
      block:
      - name: CONFIGURE | Ensure chrome directory exists
        ansible.builtin.file:
          path: "{{ firefox_config_folder_path }}/chrome"
          state: directory
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0700

      - name: CONFIGURE | Ensure tab close button is removed in userChrome.css
        ansible.builtin.lineinfile:
          path: "{{ firefox_config_folder_path }}/chrome/userChrome.css"
          create: True
          line: ".tabbrowser-tab:not([pinned]) .tab-close-button { display:none !important; }"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0664

      - name: CONFIGURE | Ensure config reads userChrome.css file
        ansible.builtin.lineinfile:
          path: "{{ firefox_config_folder_path }}/user.js"
          create: True
          regex: "toolkit.legacyUserProfileCustomizations.stylesheets"
          line: 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0664
      when: remove_close_button_from_tabs == "true"

    - name: CONFIGURE | Enable tab close button
      block:
      - name: CONFIGURE | Remove chrome directory if exists
        ansible.builtin.file:
          path: "{{ firefox_config_folder_path }}/chrome"
          state: absent
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0700

      - name: CONFIGURE | Ensure config does not read userChrome.css file
        ansible.builtin.lineinfile:
          path: "{{ firefox_config_folder_path }}/user.js"
          create: True
          regex: "toolkit.legacyUserProfileCustomizations.stylesheets"
          line: 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", false);'
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0664
      when: remove_close_button_from_tabs == "false"

    - name: CONFIGURE | Set bookmark toolbar visibility
      ansible.builtin.lineinfile:
        path: "{{ firefox_config_folder_path }}/user.js"
        create: True
        regex: "browser.toolbars.bookmarks.visibility"
        line: 'user_pref("browser.toolbars.bookmarks.visibility", "{{ toolbar_bookmark_visibility }}");'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0664

    - name: CONFIGURE | Set startup page functionality
      ansible.builtin.lineinfile:
        path: "{{ firefox_config_folder_path }}/user.js"
        create: True
        regex: "browser.startup.page"
        line: 'user_pref("browser.startup.page", {{ startup_page_option }});'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0664

    - name: CONFIGURE | Configure custom startup page
      ansible.builtin.lineinfile:
        path: "{{ firefox_config_folder_path }}/user.js"
        create: True
        regex: "browser.startup.homepage"
        line: 'user_pref("browser.startup.homepage", "{{ startup_homepage }}");'
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: 0664

